import {
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// better-auth tables (user / session / account / verification). Generated by
// `npx @better-auth/cli generate` — do not hand-edit.
export * from './auth-schema';

// --- domain tables (plan §5 Phase 1 subset, row-per-cell) ---

export const workspace = pgTable('workspace', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const base = pgTable('base', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id')
    .notNull()
    .references(() => workspace.id),
  name: text('name').notNull(),
  icon: text('icon'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdBy: text('created_by'), // user id, no FK (app-layer integrity)
});

export const table = pgTable(
  'table',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    baseIdx: index('table_base_id_idx').on(t.baseId),
  }),
);

export const view = pgTable(
  'view',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    type: text('type').notNull(), // 'grid' (Form/Kanban/Gallery later)
    name: text('name').notNull(),
    options: jsonb('options').notNull().default({}),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tableIdx: index('view_table_id_idx').on(t.tableId),
  }),
);

export const field = pgTable(
  'field',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    type: text('type').notNull(), // text | number | boolean | date | single-select
    options: jsonb('options').notNull().default({}),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tableIdx: index('field_table_id_idx').on(t.tableId),
  }),
);

export const record = pgTable(
  'record',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: text('created_by'),
  },
  (t) => ({
    // No standalone table_id index: this composite's leading column covers it
    // (dropped record_table_id_idx in migration 0012 as redundant).
    // Default view ordering is (table_id, created_at desc) — listRecordsPivoted's
    // fallback sort; a covering composite avoids a per-request sort of the table.
    tableCreatedIdx: index('record_table_created_at_idx').on(t.tableId, t.createdAt.desc()),
  }),
);

export const cell = pgTable(
  'cell',
  {
    id: text('id').primaryKey(),
    recordId: text('record_id')
      .notNull()
      .references(() => record.id, { onDelete: 'cascade' }),
    fieldId: text('field_id')
      .notNull()
      .references(() => field.id, { onDelete: 'cascade' }),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // No standalone record_id index: cell_record_field_uq's leading column
    // covers it (dropped cell_record_id_idx in migration 0012 as redundant).
    recordFieldUq: uniqueIndex('cell_record_field_uq').on(t.recordId, t.fieldId),
    fieldIdx: index('cell_field_id_idx').on(t.fieldId),
    // GIN for `value @> '[...]'` link-cell scans (record.delete cascade-clear).
    valueGinIdx: index('cell_value_gin').using('gin', t.value),
  }),
);

// Append-only log of cell value changes (plan §9). cellId is plain text (no FK):
// when a cell is deleted its history rows remain as a log (cellId dangles), per Q6.
export const cellHistory = pgTable(
  'cell_history',
  {
    id: text('id').primaryKey(),
    cellId: text('cell_id').notNull(),
    oldValue: jsonb('old_value'),
    newValue: jsonb('new_value'),
    changedBy: text('changed_by'),
    changedAt: timestamp('changed_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    cellIdx: index('cell_history_cell_id_idx').on(t.cellId, t.changedAt),
    // listByBase/listByTable page by (changed_at DESC, id DESC) — the unique id
    // is the tiebreaker that keeps offset paging deterministic when a bulk
    // write (dead-ref cleanup, backfill, import) stamps many rows identically.
    // The composite backs the full ORDER BY; it replaced the former
    // single-column (changed_at DESC) index in migration 0011.
    changedAtIdIdx: index('cell_history_changed_at_id_idx').on(t.changedAt.desc(), t.id.desc()),
  }),
);

export const attachment = pgTable(
  'attachment',
  {
    id: text('id').primaryKey(),
    // Owning base for download authorization. Nullable: rows created before this
    // column existed (download falls back to uploader-only access).
    baseId: text('base_id').references(() => base.id, { onDelete: 'cascade' }),
    filename: text('filename').notNull(),
    mime: text('mime').notNull(),
    size: integer('size').notNull(),
    storageKey: text('storage_key').notNull(),
    uploadedBy: text('uploaded_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // share.list / base deletion cascade scan attachments by base.
    baseIdx: index('attachment_base_id_idx').on(t.baseId),
  }),
);

export const baseShare = pgTable(
  'base_share',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    viewId: text('view_id'),
    token: text('token').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: text('created_by'),
  },
  (t) => ({
    tokenUq: uniqueIndex('base_share_token_uq').on(t.token),
    // share.list filters by base; base deletion cascades over shares.
    baseIdx: index('base_share_base_id_idx').on(t.baseId),
  }),
);

export const baseMember = pgTable(
  'base_member',
  {
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    role: text('role').notNull().default('editor'), // owner | editor | viewer
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    baseUserPk: primaryKey({ columns: [t.baseId, t.userId] }),
    userIdx: index('base_member_user_id_idx').on(t.userId),
  }),
);

// Bearer tokens for the agent access layer (REST /api/v1, MCP, …). A token acts
// as its creator: authorization goes through the same base_member role checks as
// a signed-in user (ADR-0010). Only the sha256 hex digest is stored — the
// plaintext `mpk_…` value is shown once at creation and never recoverable.
// userId has no FK (app-layer integrity, like the rest of the schema).
export const apiToken = pgTable(
  'api_token',
  {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    name: text('name').notNull(),
    tokenHash: text('token_hash').notNull(),
    tokenPrefix: text('token_prefix').notNull(), // first 12 chars of `mpk_…`, display-only
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => ({
    // Lookup path on every agent request: hash the presented token, seek here.
    tokenHashUq: uniqueIndex('api_token_hash_uq').on(t.tokenHash),
    userIdx: index('api_token_user_id_idx').on(t.userId),
  }),
);

// Pending collaborator invites for a base. Soft-deleted by setting acceptedAt
// (delete marks it consumed; create deactivates prior pending invites). invitedBy
// has no FK (app-layer integrity, like the rest of the schema). Token is a UUID
// without dashes (same pattern as baseShare.token).
export const baseInvite = pgTable(
  'base_invite',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    role: text('role').notNull().default('editor'), // owner | editor | viewer
    token: text('token').notNull(),
    invitedBy: text('invited_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  },
  (t) => ({
    tokenUq: uniqueIndex('base_invite_token_uq').on(t.token),
    // invite.list filters by base; base deletion cascades over invites.
    baseIdx: index('base_invite_base_id_idx').on(t.baseId),
  }),
);

export const airtableImportReceipt = pgTable('airtable_import_receipt', {
  requestId: uuid('request_id').primaryKey(),
  userId: text('user_id').notNull(),
  sourceBaseId: text('source_base_id').notNull(),
  baseId: text('base_id')
    .notNull()
    .references(() => base.id, { onDelete: 'cascade' }),
  report: jsonb('report').$type<import('../imports/airtable/types').ImportReport>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
