import {
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// better-auth tables (user / session / account / verification). Generated by
// `npx @better-auth/cli generate` — do not hand-edit.
export * from './auth-schema';

// --- domain tables (plan §5 Phase 1 subset, row-per-cell) ---

export const workspace = pgTable('workspace', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const base = pgTable('base', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id')
    .notNull()
    .references(() => workspace.id),
  name: text('name').notNull(),
  icon: text('icon'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdBy: text('created_by'), // user id, no FK (app-layer integrity)
});

export const table = pgTable(
  'table',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    baseIdx: index('table_base_id_idx').on(t.baseId),
  }),
);

export const view = pgTable(
  'view',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    type: text('type').notNull(), // 'grid' (Form/Kanban/Gallery later)
    name: text('name').notNull(),
    options: jsonb('options').notNull().default({}),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tableIdx: index('view_table_id_idx').on(t.tableId),
  }),
);

export const field = pgTable(
  'field',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    type: text('type').notNull(), // text | number | boolean | date | single-select
    options: jsonb('options').notNull().default({}),
    orderIndex: integer('order_index').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tableIdx: index('field_table_id_idx').on(t.tableId),
  }),
);

export const record = pgTable(
  'record',
  {
    id: text('id').primaryKey(),
    tableId: text('table_id')
      .notNull()
      .references(() => table.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: text('created_by'),
  },
  (t) => ({
    tableIdx: index('record_table_id_idx').on(t.tableId),
  }),
);

export const cell = pgTable(
  'cell',
  {
    id: text('id').primaryKey(),
    recordId: text('record_id')
      .notNull()
      .references(() => record.id, { onDelete: 'cascade' }),
    fieldId: text('field_id')
      .notNull()
      .references(() => field.id, { onDelete: 'cascade' }),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recordFieldUq: uniqueIndex('cell_record_field_uq').on(t.recordId, t.fieldId),
    fieldIdx: index('cell_field_id_idx').on(t.fieldId),
    recordIdx: index('cell_record_id_idx').on(t.recordId),
    // GIN for `value @> '[...]'` link-cell scans (record.delete cascade-clear).
    valueGinIdx: index('cell_value_gin').using('gin', t.value),
  }),
);

// Append-only log of cell value changes (plan §9). cellId is plain text (no FK):
// when a cell is deleted its history rows remain as a log (cellId dangles), per Q6.
export const cellHistory = pgTable(
  'cell_history',
  {
    id: text('id').primaryKey(),
    cellId: text('cell_id').notNull(),
    oldValue: jsonb('old_value'),
    newValue: jsonb('new_value'),
    changedBy: text('changed_by'),
    changedAt: timestamp('changed_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    cellIdx: index('cell_history_cell_id_idx').on(t.cellId, t.changedAt),
  }),
);

export const attachment = pgTable('attachment', {
  id: text('id').primaryKey(),
  // Owning base for download authorization. Nullable: rows created before this
  // column existed (download falls back to uploader-only access).
  baseId: text('base_id').references(() => base.id, { onDelete: 'cascade' }),
  filename: text('filename').notNull(),
  mime: text('mime').notNull(),
  size: integer('size').notNull(),
  storageKey: text('storage_key').notNull(),
  uploadedBy: text('uploaded_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const baseShare = pgTable(
  'base_share',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    viewId: text('view_id'),
    token: text('token').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: text('created_by'),
  },
  (t) => ({
    tokenUq: uniqueIndex('base_share_token_uq').on(t.token),
  }),
);

export const baseMember = pgTable(
  'base_member',
  {
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    role: text('role').notNull().default('editor'), // owner | editor | viewer
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    baseUserPk: primaryKey({ columns: [t.baseId, t.userId] }),
    userIdx: index('base_member_user_id_idx').on(t.userId),
  }),
);

// Pending collaborator invites for a base. Soft-deleted by setting acceptedAt
// (delete marks it consumed; create deactivates prior pending invites). invitedBy
// has no FK (app-layer integrity, like the rest of the schema). Token is a UUID
// without dashes (same pattern as baseShare.token).
export const baseInvite = pgTable(
  'base_invite',
  {
    id: text('id').primaryKey(),
    baseId: text('base_id')
      .notNull()
      .references(() => base.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    role: text('role').notNull().default('editor'), // owner | editor | viewer
    token: text('token').notNull(),
    invitedBy: text('invited_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  },
  (t) => ({
    tokenUq: uniqueIndex('base_invite_token_uq').on(t.token),
  }),
);
