import { index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

// better-auth tables (user / session / account / verification). Generated by
// `npx @better-auth/cli generate` — do not hand-edit.
export * from './auth-schema';

// --- domain tables (plan §5 Phase 1 subset, row-per-cell) ---

export const workspace = pgTable('workspace', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const base = pgTable('base', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id')
    .notNull()
    .references(() => workspace.id),
  name: text('name').notNull(),
  icon: text('icon'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdBy: text('created_by'), // user id, no FK (app-layer integrity)
});

export const table = pgTable('table', {
  id: text('id').primaryKey(),
  baseId: text('base_id')
    .notNull()
    .references(() => base.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  orderIndex: integer('order_index').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const view = pgTable('view', {
  id: text('id').primaryKey(),
  tableId: text('table_id')
    .notNull()
    .references(() => table.id, { onDelete: 'cascade' }),
  type: text('type').notNull(), // 'grid' (Form/Kanban/Gallery later)
  name: text('name').notNull(),
  options: jsonb('options').notNull().default({}),
  orderIndex: integer('order_index').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const field = pgTable('field', {
  id: text('id').primaryKey(),
  tableId: text('table_id')
    .notNull()
    .references(() => table.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  type: text('type').notNull(), // text | number | boolean | date | single-select
  options: jsonb('options').notNull().default({}),
  orderIndex: integer('order_index').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const record = pgTable('record', {
  id: text('id').primaryKey(),
  tableId: text('table_id')
    .notNull()
    .references(() => table.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  createdBy: text('created_by'),
});

export const cell = pgTable(
  'cell',
  {
    id: text('id').primaryKey(),
    recordId: text('record_id')
      .notNull()
      .references(() => record.id, { onDelete: 'cascade' }),
    fieldId: text('field_id')
      .notNull()
      .references(() => field.id, { onDelete: 'cascade' }),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recordFieldUq: uniqueIndex('cell_record_field_uq').on(t.recordId, t.fieldId),
    fieldIdx: index('cell_field_id_idx').on(t.fieldId),
    recordIdx: index('cell_record_id_idx').on(t.recordId),
  }),
);

// Append-only log of cell value changes (plan §9). cellId is plain text (no FK):
// when a cell is deleted its history rows remain as a log (cellId dangles), per Q6.
export const cellHistory = pgTable('cell_history', {
  id: text('id').primaryKey(),
  cellId: text('cell_id').notNull(),
  oldValue: jsonb('old_value'),
  newValue: jsonb('new_value'),
  changedBy: text('changed_by'),
  changedAt: timestamp('changed_at', { withTimezone: true }).notNull().defaultNow(),
});

export const attachment = pgTable('attachment', {
  id: text('id').primaryKey(),
  filename: text('filename').notNull(),
  mime: text('mime').notNull(),
  size: integer('size').notNull(),
  storageKey: text('storage_key').notNull(),
  uploadedBy: text('uploaded_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
